[package]
name = "chess_backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.11.5"
log = "0.4.22"

[build-dependencies]
bindgen = "0.69.4"
cc = "1.0.102"
